<?php

require_once("header.php");
?>
<section id="content"><div class="ic"></div>
    <div class="container_24">

        <div class="grid_24 prefix_1">
            <h2 class="h2 top-3">Chás:</h2>
            <figure class="image-wp">
                <img src="images/img-folha-cha-loja-alecrim-do-campo.jpg" alt="Chá Verde Loja Alecrim do Campo"/>
            </figure>
            <p>
               É preciso cuidado ao tomar chás buscando benefícios para a saúde. Nunca se deve utilizar chás com esse objetivo sem uma orientação de um profissional que conheça bem suas indicações. Da mesma maneira que as ações dos chás podem trazer benefícios, quando empregados em excesso, ou em situações equivocadas, podem ser prejudiciais à saúde.
            </p>
            <p>
                Chá é uma bebida quente introduzida pelos chineses há alguns milhares de anos. Chá vem da palavra “tchá” em chinês, que tem o mesmo significado. 
                Segundo a lenda chinesa o imperador ShenNong estava no pátio do seu palácio bebendo uma taça de água quente quando uma folha veio, trazida pelo vento, e caiu em sua taça. 
                Ele de curiosidade experimentou e surpreendeu-se com um sabor agradável. Mais ainda, a bebida deu conforto no estômago e disposição. 
                Animado com sua descoberta, mandou seus guardas encontrarem a árvore de onde tinha saído a folha, e em seguida plantou muitas mudas para que seus súditos também pudessem apreciar essa nova bebida. Estava descoberto o chá verde.
            </p>
            <h2 class="h2 top-3">Ervas:</h2>
            <p>
                Quem nunca ouviu falar de uma receita caseira “tiro e queda” contra gripe, dores de cabeça, azia, entre outros tipos de mal-estar. Essas fórmulas, geralmente transmitidas de pai para filho, têm algo em comum: o uso de plantas medicinais. A prática, ainda que muitos não saibam, tem nome, é aFitoterapia. Muitas dessas ervas têm efeito terapêutico tão eficiente quanto o de um remédio industrializado. Às vezes, a ação no organismo é melhor que a dos medicamentos alopáticos, com menos efeitos colaterais, quando administradas corretamente. 
            </p>
            <p>
                Além disso, elas têm um custo mais acessível, uma vez que podem ser cultivadas ou obtidas diretamente de fontes naturais. Essa ação pode ser benéfica ou tóxica, dependendo da quantidade ingerida, do modo de preparo e se há outros medicamentos envolvidos. Plantas aparentemente inofensiva e utilizada como remédio são comprovadamente perigosas dependendo da forma com que são administradas.
            </p>
        </div>
        
        <div class="grid_24 prefix_1">
            <h2 class="h2 top-3">Benefícios do Chá para a Saúde:</h2>
            <figure class="image-wp">
                  <img src="images/img-erva-alecrim-do-campo.jpg" alt="Folhas de Chá Alecrim do Campo"/>
            </figure>
            <p><strong>ABACATEIRO</strong> – As folhas e as frutas são ricas em proteínas e vitaminas.  É diurético, estomáquico, anti-sifilítico.  Combate o artritismo e a gota, calmante de dores, elimina urina, cálculos renais e biliares. Melhora os rins e a bexiga.  É preferível usar o chá das folhas secas, porque as verdes são estimulantes e aumentam as palpitações cardíacas.  O caroço ralado e preparado em álcool serve para fricções contra o reumatismo e nevralgias; e, torrado, o pó (uma colher de chá), combate a diarréia, gases intestinais e os vermes.  A massa do fruto ou o suco do caroço são tônicos do couro cabeludo; melhoram os cabelos e têm poder cicatrizante notável.</p>
            <p><strong>AGONIADA</strong> – Atuante nas histerias, na asma, na menstruação difícil, nas febres intermitentes, clorose e adenite.  Substituta da quinina.</p>
            <p><strong>ALCACHOFRA</strong> – Enérgico diurético, eliminador do ácido úrico, do reumatismo e das febres:  nos distúrbios hepáticos e digestivos; aumenta a secreção biliar, a flor é boa salada.  Faz baixar a pressão arterial.  Evitar seu uso durante o período de lactação. </p>
            <p><strong>ALFAVACA</strong> – O chá é diurético, estimulante, sudorífico; prepara-se para gargarejos nas dores de aftas; ajuda o estômago, os intestinos e elimina a areia dos rins.  Muito usada para banhos, emplastos e bafos contra inflamações dos testículos, reumatismo, paralisias, pernas inchadas. </p>
            <p><strong>ALFAZEMA</strong> – Anúria, amenorréia, asma, afecções do fígado e baço; nervosismo, dor de cabeça, neurose cardíaca, ventuosidade.  As mulheres têm nela um regulador das menstruações.  Sua essência combate piolhos e outras parasitas. </p>
            <p><strong>AMOR-PERFEITO</strong> – Conhecida também com o nome:  flor-da-trindade, violeta de três cores.  Os seus valores terapêuticos são:  purificador do sangue, algo laxante, atua sobre as glândulas linfáticas, mau funcionamento dos rins com retenção de líquidos (edema).  O povo faz uso deste medicamento na crosta láctea das crianças, eczema que dá no rosto e na cabeça com coceira.  Usado contra a vontade contínua de urinar, emissão abundante de urina fétida, palpitações do coração, poluições noturnas com sonhos que causam inquietação.  Para as indicações acima usa-se o chá com 10 g de flores ou 20 g de folhas para um litro de água a ferver, 3 a 4 xícaras por dia.</p>
            <p><strong>AMOR–DO–CAMPO</strong> – Ainda com o nome de amor-agarrado, é usado na medicina como depurativo do sangue, diurético, elimina corrimento da uretra e da bexiga, rins e doenças do fígado.  É benéfica em aplicações em moléstias de pele como herpes e impigens.</p>
            <p><strong>ANIS</strong> – Chamado de "Erva-doce".  Chá de uma colher de semente combate:  cólicas das crianças, diarréia crônica; provoca sono, evita desmaios, aumenta o leite das mães; é digestivo e contra azia.  Tem ação sobre o cérebro, facilitando trabalhos intelectuais.  Aumenta a urina; estomacal e emenagogo. </p>
            <p><strong>APERTA-RUÃO</strong> – Esta planta é fortemente adstringente.  Externamente serve seus cozimento para lavar feridas, em banhos, fazer bochechos.  Combate o mau hálito, diarréia, gonorréia e males do fígado.</p> 
            <p><strong>ARARUTA</strong> – É do rizoma que se extrai uma fécula branca, a tapioca comercial, empregada nas confeitarias, na confecção de biscoitos, bolos e doces.  Seu mingau fortalece os fracos, crianças e idosos.  É muito recomendado para as crianças com problemas intestinais, dispepsias.  Aplica-se também em feridas purulentas; é contraveneno de cobra.</p> 
            <p><strong>ARNICA</strong> – Nos traumatismos, golpes e ferimentos; machucaduras; aplicar e tomar; nevralgias; anemia; coqueluche; paralisia; hemorragias e vias urinárias; trombose; em caso de derrame, reabsorve o sangue.  O povo chama a várias ervas com este nome, mas todas tem propriedades idênticas.</p> 
            <p><strong>AROEIRA</strong> – Não é aquela que causa alergias.  Indicada para banhos no reumatismo, dor ciática, diarréias e disenterias; é adstringente.  A casca é de valor contra as feridas, tumores, inflamações em geral, hemorragias internas, cicatrizante e problemas respiratórios.  Os jesuítas preparavam com a resina o famoso bálsamo das missões, anacauita é boa também.</p> 
            <p><strong>ARTEMÍSIA</strong> - Bom para o sistema nervoso, anemia, fraqueza em geral, fígado; provoca menstruações suprimidas, afecções uterinas; elimina gases; combate a verminose (chá das flores).  O chá de artemísia, tomado durante oito dias antes do parto, aumenta as secreções das mucosas genitais e facilita o parto. </p>
            <p><strong>ASSA-PEIXE, MATA-CAMPO</strong> – Contra a gripe pulmonar, tosses rebeldes, bronquites e hemorróidas; em banhos nas afecções do útero; alivia pontadas, dores no peito e nas costas, amarelão (raiz).  O cozimento da raiz serve para estancar sangue, desfazer golpes e machucaduras. </p>
            <p><strong>BARDANA</strong> – Provoca suor; diurética, aumenta a urina e é ótimo contra cálculos renais, moléstias da pele; grande depurativo do sangue, do fígado, dos rins; remédio anti-sifilítico; folhas, untadas com azeite ou só seu suco, aplica-se sobre feridas, reumatismo, ajuda o crescimento e evita a queda do cabelo. </p>
            <p><strong>BOLDO DO CHILE</strong> – É tônico; afecções e cálculos do fígado, prisão de ventre, gases intestinais, digestão difícil; dá sono suave; febre; três xícaras por dia.  O boldo-do-brasil é de diferentes propriedades, forte calmante e é uma droga (moderação no uso).</p>
            <p><strong>CALÊNDULA, MARGARIDA-DOURADA, MAL-ME-QUER</strong> – É excitante, expectorante, antiespasmódica, anti-abortiva, fortalece o útero; ótimo remédio na idade crítica, nas anemias nervosas; o suco das folhas se aplica sobre calos, verrugas, pólipos e internamente como chá.  Externamente é um poderoso antisséptico, contra inflamações das vistas, feridas e chagas cancerosas, dor de garganta, icterícia; combate qualquer alergia.  São muito usados os sabonetes e as pomadas de calêndula. </p>
            <p><strong>CAMOMILA</strong> – Indigestões, gases, debilidades do estômago, falta de apetite, cólicas, histerismo; contra vermes intestinais, doenças do útero e dos ovários; é tônica. </p>
            <p><strong>CANA-DO-BREJO</strong> – Sudorífica; diurética; na sífilis; pedras na bexiga; inflamações dos rins; falta de regras; combate a arteriosclerose.  Usam-se as raízes em pó para em cataplasma curar hérnias, inchaços e contusões.</p> 
            <p><strong>CAPIM-CIDREIRA, CAPIM-CIDRÓ, CAPIM-LIMÃO</strong> – Sedativo; faz suar; combate gases intestinais; tosse, perturbações urinárias, histerismo; tomá-lo com muita freqüência enfraquece a pessoa.</p> 
            <p><strong>CARDOMOMO</strong> – É uma espécie de cana, como o gengibre.  O povo comumente chama esta planta de noz-moscada, mas não é.  A semente, que raramente dá, tem o gosto fraco de noz-moscada.  Os egípcios a mascavam para conservar os dentes brancos e a boca aromática.  Os romanos a usavam como condimento digestivo e para aromatizar e para aromatizar licores.  O chá das folhas estimula o apetite, alivia gases intestinais, normaliza distúrbios gástricos.  É um auxiliar de tempero para dar melhor gosto aos alimentos.</p> 
            <p><strong>CARQUEJA</strong> – Desobstruente do fígado; febrífuga; contra anemia, fraqueza intestinal e perda de sangue:  10 g de carqueja, 10 g de fedegoso, 4 folhas de laranja e 10 g de sal e coar, é um remédio contra tosse.  Útil na diabete.  É estomacal e cura inflamações das vias urinárias, baço, bexiga e rins, chagas venéreas e leprosas. </p>
            <p><strong>CATUABA</strong> – Tônica na falta de potência sexual, neurastenia, sono agitado, memória fraca; estimulante, aperiente, fortalece as pessoas esgotadas e fracas em geral. </p>
            <p><strong>CAVALINHA</strong> – Chamada também de cauda-de-cavalo, rabo-de-cavalo.  Cresce de preferência nos terrenos brejosos, à beira dos riachos.  São conhecidas umas 30 espécies.  Contém sílica em grande quantidade.  É remineralizante do organismo depauperado, de modo especial, para os tuberculosos e gente que sofre dos pulmões.  Possui virtudes, propriedades hemostáticas, diuréticas, digestivas, depurativas.  Tem ainda indicações contra a tuberculose, doenças dos ossos, com úlceras gástricas e intestinal, perdas de sangue (reto, nariz e boca), ajuda no tratamento das moléstias da bexiga e dos rins, incontinência noturna da urina das crianças e pessoas de idade.  O Pe. Kneipp em sua medicina natural tinha a cavalinha na mais alta consideração.  Prepara-se um chá com 20 a 50 g por litro e toma-se 3 a 4 xícaras por dia. </p>
            <p><strong>CHAPÉU-DE-COURO, CHÁ-MINEIRO</strong> – Contra moléstias da pele, reumatismo, artritismo, sífilis, afecções dos rins e bexiga; depurativo do sangue.  Ajuda a baixar a pressão alta.  Evita a arteriosclerose.  O rizoma triturado usa-se aplicação sobre hérnia.</p>  
            <p><strong>COMINHO</strong> – Usado como condimento é praticamente como o anis.  É carminativo (combate os gases), diurético, estomocal, provoca o mênstruo.  Em cataplasma faz desinflamar os seios e os testículos.  Dose normal:  3 g por xícara.  Há povos que o usam para aromatizar queijos e pães.</p> 
            <p><strong>CONFREI, CONSÓLIDA, CONSOLDA</strong> – Erva rica em proteínas, ótimo fortificante, remineralizante, útil nas anemias, aumenta os glóbulos vermelhos.  Ativa o crescimento das células, fortalece os tecidos da pele.  Pode-se tomar seu suco, como chá, ou em salada.  Como remédio, ainda tem aplicações externas para curar feridas, como cicatrizantes de cortes, queimaduras, fraturas de ossos (aplica-se a massa da raiz junto com as ataduras); internamente:  úlceras e inflamações dos intestinos, ovários, rins e bexiga, hemorróidas e hemorragias internas.  Pode-se associar com outras ervas curativas como tansagem.  Não aconselhamos seu uso interno por longo tempo continuado. </p>
            <p><strong>CRAVO-DA-ÍNDIA</strong> – Excitante aromático; alivia dor de dente, digestivo, nas fraquezas sexuais; contra gases, promove fluxo menstrual. </p>
            <p><strong>DENTE-DE-LEÃO, AMOR-DOS-HOMENS</strong> – Usado desde a antiguidade nas doenças do fígado e dos rins; depurativo do sangue e melhora o sangue fraco, o apetite, combate gases intestinais, prisão de ventre; cura feridas (o leite), câncer da bexiga; benéfica contra o diabete; seu suco tomado em água é um vantajoso fortificante dos nervos, do cérebro e das vistas; rico em vitaminas e sais minerais.  Da raiz torrada se faz um saudável café.</p> 
            <p><strong>DOURADINHA-DO-CAMPO</strong> – Diurético, eficiente nas dificuldades de urinar, inflamações da bexiga e elimina as pedras.  Cura as endemas e cremas.  Benéfica nas afecções pulmonares, bronquites e tosses, como para combater a sífilis e amolecer tumores.</p> 
            <p><strong>ENDRO</strong> – Combate o soluço e ânsias de vômito (tomar o chá quente).  A infusão das sementes para bochechos e gargarejos; cura as inflamações da garganta e da boca.  Seu chá, tomado após as refeições, alivia dores intestinais, gases e hiperacidez do estômago.  Aumenta o leite das mães.  Semelhante ao funcho. </p>
            <p><strong>ERVA-CIDREIRA, MELISSA</strong> –  Afecções do estômago, nervos insônia, dores, desmaios, palpitações do coração, resfriados, contra gases; folhas secas colocadas sobre as pálpebras aliviam a dor.</p>
            <p><strong>ERVA-DE-BICHO OU PIMENTA D’ÁGUA</strong> – Diurética; hemorragias gástricas, varizes, aperiente, na falta de menstruação, para clisteres e em banhos contra hemorróidas, vermes e disenterias sangüinolentas; afecções das vias urinárias.</p>
            <p><strong>ERVA-DE–PASSARINHO</strong> – As folhas e flores contra:  diabetes, histeria, hemorragias, feridas (lavar), pneumonia, arteriosclerose, asma, afecções da pela, frieiras, úlceras e moléstias uterinas.  Remédio para baixar a pressão do sangue.  Exerce ação tônica-sedativa sobre o coração e é eficiente na idade crítica, transtornos nervosos das mulheres e mesmo em casos de câncer.  Iniciar com dose fraca.</p> 
            <p><strong>ERVA-DE-SANTA-MARIA OU ERVA-DE-BICHA</strong> – 40 espécies.  Poderoso vermífugo, 1 colher de semente ou feito chá por dose, ou chá das folhas em jejum; combate doenças nervosas, hemorróidas, varizes, dores, indigestão; o suco (duas colheres) cura manchas dos pulmões, facilita menstruações; toma-se ao fraturar ossos.  Contra vermes, toma-se 2 dias seguidos de manhã ou à noite.  É eficaz na angina do peito, palpitações do coração, má circulação, sono agitado, zumbido nos ouvidos. </p>
            <p><strong>ERVA-MATE</strong> – O chimarrão reanima as forças corporais, estimulante do cérebro, resistência a fadiga, ativa a circulação.  Mate cozido é bom para lavar feridas, desinfetante, contra insônia, sudorífica, efeito bom para o fígado e os rins.  Contém cafeína, por isso, vicia e, tomando demais, ataca os nervos. </p>
            <p><strong>ESPINHEIRA-SANTA, MAYTENUS</strong> - Ulcerações do estômago, afecções da pele, feridas, desinfetante, cicatrizante, bom para os rins, acalma dores, neutraliza o ácido, remédio de grande valor.  Indicada para corrigir os viciados em álcool, 1 litro por dia 3 semanas seguidas.  Diminui o leite materno em mulheres que amamentam. </p>
            <p><strong>EUCALIPTO</strong> – Antiespasmódico.  Nevrites, combate as febres, gripes, diabete, bronquite, asma, gangrena pulmonar, males da bexiga, dor das cadeiras, reumatismo em fricções.  Mascar suas folhas alivia a dor e inflamação da garganta.  É anti-séptica. </p>
            <p><strong>FUNCHO</strong> – É semelhante à erva-doce, anis; aperiente, contra gases, digestivo, bom para crianças, raiz é diurética, aumenta o leite das mães, afecções das vias urinárias.  Guarde sementes secas em casa. </p>
            <p><strong>GERGELIM</strong> – Planta asiática, aclimatada no Brasil.  As sementes torradas servem para fazer bolos de agradável sabor.  O óleo de gergelim é de elevado poder nutritivo, tônico nervino, consumido no mundo inteiro como alimento.  Para as mulheres tem efeitos abortivos e em geral é laxativo.  Tem ação afrodisíaca.  O seu óleo raramente fica rançoso.  Aplica-se nas dores reumáticas e tumores.  Ainda é recomendado nas queimaduras, dor de ouvido e clisteres. </p>
            <p><strong>GERVÃO</strong> – Dores do fígado e estômago, febres, prisão de ventre; diurético; lavar a cabeça com o cozimento, facilita a menstruação, tônico estimulante; o suco com sal aplica-se sobre tumores e furúnculos. </p>
            <p><strong>GINSENG</strong> – Planta originária da Coréia e Manchúria.  A planta selvagem que contém as melhores propriedades medicinais.  A medicina chinesa antiga vê no jinsão uma valiosa panacéia capaz de curar inúmeras doenças, restabelecer a vitalidade física, mental e genésica.  Afrodisíaco e tônico.  Utiliza-se a raiz.  Existem pastilhas. </p>
            <p><strong>GUACO</strong> – Contra reumatismo, albuminúria, nevralgias, dá xarope contra tosse, gripe, contra mordedura de cobra, cicatrizante, calmante em geral. </p>
            <p><strong>GUANDU, ERVILHA-DE-SETE-ANOS, FEIJÃO-ANDU, FEIJÃO-DE-ÁRVORE</strong> – O chá de suas folhas, 25 a 30 folhas por litro, indicado como depurativo do sangue, diurético, contra tosse, inflamações da garganta, dor de dente e curar úlceras.  A raiz é benéfica na clorose e males do fígado.  A planta toda, sobretudo a semente, é altamente nutritiva, rica em proteínas, ferro e cálcio. </p>
            <p><strong>GUARANÁ</strong> – Excita o coração, contra nevralgias, diarréias, hemorragias, desinfetante intestinal, previne arteriosclerose.  Remédio para quem urina na cama.  Puro, contém muita cafeína.</p> 
            <p><strong>HORTELÃ</strong> – Existem 25 espécies.  Estimulante, tônica, digestiva, prisão de ventre, vermes, calmante e contra reumatismo; com o bagaço, limpa-se feridas. </p>
            <p><strong>IPÊ-ROXO, IPÊ-AMARELO, PAU-D’ARCO</strong> – É adstringente; o cozimento das cascas combate estomatites, nevralgias, sífilis, cancro, câncer, úlceras, reumatismo, diabetes (contêm insulina), pedras vesicais, inchações dos pés dos pés, elimina toxinas, aumenta os glóbulos vermelhos e tem ação sobre as células que crescem desordenadamente, evita a formação de tumores, doenças de pele, impigens; famoso depurativo do sangue.</p>  
            <p><strong>JABORANDI</strong> -  O jaborandi é um dos melhores sudoríferos conhecidos, a transpiração é abundante como a salivação também.  É um bom remédio contra gripe, laringite, bronquite, edema pulmonar, caxumba.  Externamente é um tônico dos cabelos, usa-se uma tintura alcoólica.  Com a decocção da planta toda banham-se as pernas paralisadas, é um bom estimulante circulatório. </p>
            <p><strong>JASMIM</strong> – Diurético, estimulante, combate a falta de ar; flores dão xarope em gargarejos, inflamações das amígdalas, doenças do útero, ovários e em lavagens vaginais.</p> 
            <p><strong>MACELA</strong> – Indigestões, males do estômago, inapetência; sumo nas epilepsias, tônico amargo, perturbações gástricas como disenterias e diarréias.  É a camomila brasileira.  É emenagoga, anti-inflamatória, antisséptica e diminui a taxa de colesterol. </p>
            <p><strong>MALVA</strong> – Calmante dos nervos e dores em geral.  Tem virtudes emolientes, para cataplasmas, inflamações do estômago, da vista, dor de dente, da boca das gengivas, da garganta, dos intestinos, da bexiga, dos rins, da pele, irrigação nas inflamações da vagina, banhos nas inchações das pernas, desinfetante posto sobre feridas e úlceras, faz emagrecer sem prejudicar o coração (tomar 30 a 40 dias).  Combate inflamações dos ouvidos e das pálpebras.</p> 
            <p><strong>MANJERICAO</strong> – Contra gases intestinais e do estômago, excitante, tônico, digestivo, nas fraquezas, cozimento das raízes serve para estancar o sangue.</p> 
            <p><strong>MANJERONA</strong> – Indicada nas fraquezas musculares e dos nervos, combate resfriados, cólicas intestinais, males do estômago, insônia, incontinência dos instintos sexuais; reumatismo; o excesso prejudica o sistema nervoso das crianças e provoca sono artificial. </p>
            <p><strong>MARACUJÁ</strong> – Calmante para dores em geral, insônia; diurética, desinfetante; semente e raiz são vermífugas; sucos são um agradável refresco. </p>
            <p><strong>MARAPUAMA</strong> – Tônico dos nervos e dos músculos; disenteria, reumatismo, paralisia, cólica menstrual, na impotência sexual. </p>
            <p><strong>NOZ-MOSCADA</strong> – Digestiva, estimulante, contra gases; elabora-se um ungüento contra o reumatismo.  Temperar sopa e em fricções em casos de dores e de gota.</p> 
            <p><strong>PAPOULA</strong> – Sementes comidas com pão conciliam o sono; calmante; contra tosse, asma, alivia as dores mesmo do câncer; as cabeça do fruto são narcóticas; do leite se extrai o ópio.</p> 
            <p><strong>PICÃO, AMOR-DE-MULHER, PICO-PICO</strong> – Usado contra reumatismo, afecções da bexiga, pedras na vesícula ou nos rins, dor de barriga, má digestão, desobstruente do fígado, febres, ingurgitamento das glândulas mamárias; toda planta recomendada contra a icterícia (amarelão), bronquite, asma; o suco das folhas é usado para curar feridas e em gargarejos, contra as amígdalas.  Ótimo remédio contra o diabete.  O picão-branco tem as mesmas propriedades.</p>
            <p><strong>PIMENTA-DO-REINO</strong> – Estimulante forte, tônica; sudorífica; afecções do estômago e febres, em gargarejos junto com limão é contra a inflamação das amígdalas.</p>
            <p><strong>QUEBRA-PEDRA</strong> – elimina catarros vesicais, cálculos do fígado, areia dos rins e da bexiga, alivia as dores de cadeira e das juntas e a hidropisia.  Combate dor de barriga, azia, prostratite.  Chá das folhas e das sementes é indicado contra diabetes. </p>
            <p><strong>SALSA</strong> – Usadíssimo, condimento.  Riquíssima em vitaminas e sais minerais com ferro; por isso, recomendada aos anêmicos, fracos e nervosos; abre o apetite; boa para a memória, favorece a digestão, tanto as folhas como a raiz.  Seu chá combate as febres da primavera e outono, o amarelão, a retenção da urina, a obesidade; provoca suor, gases intestinais, inchaços de fígado, estimula as contrações uterinas.  O suco tomado em leite acalma a asma, levanta o espírito após a embriaguez.  Externamente, se usa em cataplasmas ou compressas para curar úlceras, mesmo cancerosas, chagas rebeldes, machucaduras, pancadas, contusões.  Contra a dor de dente (colocam-se folhas esmagadas com um pouco de sal no ouvido do lado em que dói o dente), uma bolinha posta no nariz faz estagnar a hemorragia nasal. </p>
            <p><strong>SALVA, SÁLVIA</strong> – Desta erva, antes de Cristo, já se dizia:  "De que pode morrer o homem tendo um pé de salva à sua porta?"  Com as folhas prepara-se um chá e toma-se quente, contra gripes, resfriados, todo tipo de febres, problemas digestivos, gases intestinais, dor nos membros; estimulante dos nervos; aumenta a capacidade intelectual; cólicas menstruais, deficiências cardíacas, debilidade sexual, deficiências ovarianas, fortalece o útero, anti-abortiva , reguladora da tensão arterial, tem ação sobre o pâncreas em caso de diabete.  Fumando as folhas secas, alivia a sobre o pâncreas em caso de diabete.  Fumando as folhas secas, alivia a tosse asmática e esfregando com suas folhas os dentes os branqueia e fortalece as gengivas; esfregam-se também as folhas no espinhaço das crianças retardatárias ou se lhes dá banhos com o cozimento de salva.  Com seu suco, fabricam-se pomadas que se aplicam em úlceras, feridas, varizes e toda classe de paralisias.  Apreciado condimento. </p>
            <p><strong>SENE</strong> – Possui propriedades purgativas, laxativas, depurativas e febrífugas, tomando-se o chá das folhas.  Uma colher de suco das folhas, tomada três vezes ao dia, ajuda a eliminar as manchas do corpo.  É planta abortiva.  Seu uso forte não é recomendado na gravidez. </p>
            <p><strong>SETE-SANGRIAS</strong> – Existem 14 espécies.  Não confundir com a árvore sete-sangrias.  Sete-sangrias é usada contra febres, moléstias venéreas, sífilis; sudorífica; diurética, faz baixar pouco a pouco a pressão alta, combate o colesterol, ajuda a emagrecer, alivia e fortifica o coração, depurativa do sangue, limpa os intestinos e rins, eficiente contra diarréia e reumatismo. </p>
            <p><strong>SOJA</strong> - É aproveitada com alimento, seja como óleo, leite, queijo, farinha; entra em muitas receitas culinárias e de rações para animais.  Recomendada para os fracos, diabéticos, doenças de pele, arteriosclerose.</p> 
            <p><strong>STÉVIA</strong> – Esta planta vegeta mais no Sul do Mato Grosso e no Paraguai.  Analisado em laboratórios se constatou ser ela 180 a 300 vezes mais doce que o açúcar de cana.  É pois, adoçante natural, superior a sacarose no tratamento do diabete.  Não possui valor calórico, atua como calmante sobre o sistema nervoso, é diurética, tonifica o sistema vascular, indicada contra a pressão alta, insônia, depressão, fadiga cerebral, estimula as funções digestivas, favorece a eliminação de toxinas e do colesterol.  As índias a usavam para evitar a gravidez. </p>
            <p><strong>TANSAGEM, TANCHAGEM, CINCO-NERVOS</strong> – Existem 12 espécies.  Na Índia, é uma das ervas mais usadas pelas suas propriedades medicinais.  É adstringente, combate qualquer inflamação dos ouvidos, dos olhos, da conjuntivite, das gengivas, das garganta, das amígdalas, da faringe, do estômago, dos intestinos, dos rins, da bexiga e das hemorróidas.  Externamente, se usa o suco das folhas ou o cozimento para curar feridas, doenças de pele, crosta na cabeça, infecção vaginal, nevralgias das mamas, câncer dos seios, úlceras, câncer interno; cataplasmas com as folhas e com farinha.  Benéfica na incontinência da urina.  Uma colher de sopa de semente serve como especial remédio contra diarréia, cólica infantil, febres intestinais, gripes, apendicite crônica, inflamações nos ovários e bexiga, hemorróidas.  As raízes são tônicas.  Os fumantes têm nela, tomando bastante chá, um desintoxicante da nicotina e remédio para vencer o seu vício.  Combate ainda a tosse, a asma e a tuberculose.  Sua pomada é bem eficiente para curar feridas.</p> 
            <p><strong>TARUMÃ, CINCO-FOLHAS</strong> – É um dos melhores depurativos do sangue, diurético, sangue grosso, sangue agitado, crianças que babam (chá), combate pressão alta; a raiz é tônica, febrífuga, contra inflamações da bexiga e do útero de diversas doenças da pele.  As frutas são comestíveis e para as mesmas doenças.  As mulheres, na idade crítica, encontram nele favorável solução. </p>
            <p><strong>URUCU, COLORAU</strong> – O pó da semente é um bom condimento para dar cor ao arroz.  Chá das sementes tem bom efeito nos males do coração, prisão de ventre, hemorragias, afecções do estômago, como expectorante e males do peito.  É contra veneno da mandioca brava, antídoto do ácido cianídrico.  Os índios o usam para se pintar e, com isso, se defender contra picadas dos mosquitos. </p>
            <p><strong>VANILA, BAUNILHA</strong> – A vanila é uma orquídea que produz uma vagem que só depois de seca é aromática.  A vanila artificial é que mais se usa em doces.  Esta, natural, tem como propriedades ajudar a estimular o apetite, tonificar o estômago e os intestinos e sobretudo fluidificar a secreção biliar.  O pó ou a tintura feita das vagens é uma delícia em bolos e doces. </p>
            <p><strong>ZIMBRO</strong> – As bagas são as partes mais usadas desta planta.  Tem indicações tônicas, diuréticas, digestivas, antissépticas.  Eficaz na dificuldade de urinar, na insuficiência renal crônica, contra cálculos renais, bronquite crônica, reumatismo, doenças de pele especialmente psoríase e eczema crônico (em forma de pomada).  O óleo extraído das bagas atua em aplicações externas como linimento balsâmico.  Com 20 g de bagas esmagadas prepara-se uma ilusão para 1 litro de água, recomenda-se tomar no intervalo das refeições. </p>
            <ul class="lista-chas">
                <li>
                    <img src="images/img-cha-produto-alecrim-do-campo.jpg" alt="Lista Chas Alecrim do Campo"/>
                </li>
                <li>
                    <img src="images/img-cha-produto-alecrim-do-campo-02.jpg" alt="Lista Chas Alecrim do Campo"/>
                </li>
                <li>
                    <img src="images/img-cha-produto-alecrim-do-campo-03.jpg" alt="Lista Chas Alecrim do Campo"/>
                </li>
            </ul>
            <div class="of-chas">
                <a class="link-chas" href="linha-chas.php" title="Confira a lista completa de Chás">Confira a linha completa de Chás</a>
            </div>
        </div>
        <div class="clear"></div>
    </div>
</section> 
</div>
<?php

require_once("footer.php");
?>